#!/usr/bin/env python3

#
# Ioreth - An APRS library and bot
# Copyright (C) 2020  Alexandre Erwin Ittner, PP5ITT <alexandre@ittner.com.br>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#


import sys
import logging

logging.basicConfig(
    level=logging.INFO, format="%(asctime)-15s %(levelname)s: %(funcName)s %(message)s"
)
logger = logging.getLogger(__name__)

from ioreth.bot import ReplyBot


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: %s <config-file.conf>" % (sys.argv[0]))
        exit(1)
    b = ReplyBot(sys.argv[1])
    b.connect()
    b.loop()
