#!/usr/bin/env python3

import sys
import logging

from ioreth.bot import ReplyBot

logging.basicConfig(
    level=logging.INFO, format="%(asctime)-15s %(levelname)s: %(funcName)s %(message)s"
)
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: %s <config-file.conf>" % (sys.argv[0]))
        exit(1)
    b = ReplyBot(sys.argv[1])
    b.connect()
    b.loop()
